server:
  port: 8889
oauth:
  server: http://118.24.1.170:8888
  token: /oauth/token
  authorization: /oauth/authorize
  token-info: /oauth/check_token
  client-id: lesson-cloud
  client-secret: lesson-cloud-secret
  redirect-uri: http://127.0.0.1:8081/#/login
  scope: READ
  logout-uri: /oauth/logout
  logout-redirect-url: http://127.0.0.1:8081/#/logout
  security: false
